<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Server maintenance in progress_appFrame</name>
   <tag></tag>
   <elementGuidId>7d9b9926-8d84-4f15-8ece-bd6e246c4022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#appFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='appFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;NorthStar Application&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2a27fad5-7069-4ee0-8e7e-b4d4aae6c013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>appFrame</value>
      <webElementGuid>b58db050-8942-4eef-b581-0c9e408a5fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Admin/login.jsp?fromEmployeeApp=false&amp;device=0&amp;deviceToken=</value>
      <webElementGuid>d75e6433-7759-4e4d-bb89-b561ed58ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de69accf-07e8-41ca-a6e1-2a00ccff78df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>d5b3f11d-547e-4428-b766-c13358b24873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>40204233-a503-44ad-9891-9179ca4f2b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c8ca2ba5-cf32-4b17-b7ff-855301622fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>NorthStar Application</value>
      <webElementGuid>807b0da2-27d7-4136-8c07-1beef48b1a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appFrame&quot;)</value>
      <webElementGuid>b87f7947-5981-4af6-b2df-bf62d2b637a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='appFrame']</value>
      <webElementGuid>29f6305a-b057-4546-b075-f977e1c11e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0c38d1d7-4fe8-4d9f-aac3-d5d7c1651514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'appFrame' and @src = 'Admin/login.jsp?fromEmployeeApp=false&amp;device=0&amp;deviceToken=' and @title = 'NorthStar Application']</value>
      <webElementGuid>d480b81e-9702-45cc-b39a-9f6319063487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
