<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create PO</name>
   <tag></tag>
   <elementGuidId>1b12ed0e-c783-44a6-ab3b-6b27dd21b874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moduleName-9-nav']/div/div/div/section[3]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Create PO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1efd607-8cb3-4d0b-b883-360fa9907fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../t/9-4-1/Purchasing/POCreationController.jsp?func=New</value>
      <webElementGuid>c93c14fd-a51a-4c25-974c-af071dda3ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduleLinkPageName</value>
      <webElementGuid>5f8de1bf-8c5b-47ad-a1d5-dcf90d039b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-moduleid</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3e493825-1b01-4eca-bce2-852475d35f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maintabid</name>
      <type>Main</type>
      <value>164</value>
      <webElementGuid>34d1da28-d416-4c7e-b76e-bc23e6bdfa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtabid</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>3778cd25-2383-4057-b864-ca1fc083a1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modulename</name>
      <type>Main</type>
      <value>Purchasing</value>
      <webElementGuid>27eac775-05d1-42a1-a91f-c1d5709036ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create PO</value>
      <webElementGuid>d7ed7a48-99d2-4edc-a781-8e93b922c012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleName-9-nav&quot;)/div[@class=&quot;moduleLinkDiv&quot;]/div[@class=&quot;linkBody&quot;]/div[@class=&quot;section&quot;]/section[3]/ul[@class=&quot;moduleLinkInnerDiv&quot;]/li[@class=&quot;moduleLinkInnerList&quot;]/a[@class=&quot;moduleLinkPageName&quot;]</value>
      <webElementGuid>21913022-cb65-4370-a91e-6d7876c1a4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Create PO/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>648b35a0-f98d-46c3-bba8-fd500519b50e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moduleName-9-nav']/div/div/div/section[3]/ul/li[2]/a</value>
      <webElementGuid>5d78e433-be17-4634-8ebc-9d3d1b8924f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create PO')]</value>
      <webElementGuid>91b46e0c-a48f-4a19-a74f-71f7166b17a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Blanket PO'])[1]/following::a[1]</value>
      <webElementGuid>cf5afa43-0b34-4cf7-be7c-2adf430d7b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[10]/following::a[2]</value>
      <webElementGuid>feb9c1e2-03a7-4c9a-8189-312b53d02c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Receiving with PO'])[1]/preceding::a[1]</value>
      <webElementGuid>9d2922fa-5c7e-4900-b010-976175b1160c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Receiving without PO'])[1]/preceding::a[2]</value>
      <webElementGuid>71ef29c1-f2e2-47b0-9b5c-f1a5506e72f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create PO']/parent::*</value>
      <webElementGuid>005961b4-897e-4d1f-96e3-1d36992e4f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../t/9-4-1/Purchasing/POCreationController.jsp?func=New')]</value>
      <webElementGuid>2c890813-41ac-45a7-8846-5515f4535881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/section[3]/ul/li[2]/a</value>
      <webElementGuid>2c5e7a96-e959-46d7-89b6-dd2c20581430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../t/9-4-1/Purchasing/POCreationController.jsp?func=New' and (text() = 'Create PO' or . = 'Create PO')]</value>
      <webElementGuid>53b98b69-5d60-47b2-bfbf-417bf6c8280c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
