<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm_landingFrame</name>
   <tag></tag>
   <elementGuidId>fd149725-04c9-469e-b361-05ad9611d16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landingFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='landingFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;landingFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e589d4ef-1e6c-42de-a0c2-21ef0253c5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>6937af1c-0cd9-4b30-bcc3-b405501829c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>52b08048-1d6a-426b-9c90-1104add0732a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../t/9-4-1/Purchasing/POCreationController.jsp?func=New</value>
      <webElementGuid>82ae796a-1275-4c96-bad6-137ade2fe77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>closeIt(this.contentWindow.location)</value>
      <webElementGuid>3c12d8a2-03ea-42fa-8390-0449b1160075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingFrame&quot;)</value>
      <webElementGuid>e0018208-bebc-4fa8-8c2b-67803f62e7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Create PO/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>0ce2b000-7149-4e1f-b291-91aa0655d891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='landingFrame']</value>
      <webElementGuid>316cb69a-f60a-487c-8264-fc74428eafaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/iframe</value>
      <webElementGuid>5db07f12-e7c7-4e33-8c4c-93eda3e9b0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/iframe</value>
      <webElementGuid>30a0d45e-4390-4d72-a5ed-c4fb8c7a3cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'landingFrame' and @name = 'landingFrame' and @src = '../../t/9-4-1/Purchasing/POCreationController.jsp?func=New']</value>
      <webElementGuid>7092a783-b33d-4ecc-a593-9d513be4eb84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
