<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm_landingFrame</name>
   <tag></tag>
   <elementGuidId>17546f87-96c0-481b-80dc-a37d1e79fa00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='landingFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#landingFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;landingFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6b8dd6bd-9cae-46cf-9737-1e6305e7973a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>f378cfe5-2ab8-48b3-9c8f-86c76a803515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>033a1420-80ff-4488-94b5-10be8d9544a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../t/4-1-1/Accounting/AP/vendorCreation.jsp?func=New</value>
      <webElementGuid>fd9cafba-125e-4c72-ac72-d7b5e2cd8d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>closeIt(this.contentWindow.location)</value>
      <webElementGuid>59257281-7f5a-4148-9a4d-b0545860d103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingFrame&quot;)</value>
      <webElementGuid>5891c456-17bf-4a31-8df4-84a83d335265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Create Vendor/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>f7bb6023-7c4a-4f6b-a39c-9611f1f7aa26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='landingFrame']</value>
      <webElementGuid>d4dcff15-80cc-4e66-bcb4-050982fda7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/iframe</value>
      <webElementGuid>256e3d8c-8396-445c-aa6a-4759f4961db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/iframe</value>
      <webElementGuid>222bb5c6-556d-4936-bdea-1e6108d8f06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'landingFrame' and @name = 'landingFrame' and @src = '../../t/4-1-1/Accounting/AP/vendorCreation.jsp?func=New']</value>
      <webElementGuid>7232248d-530a-419e-94b3-37afdd391b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
