<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Event</name>
   <tag></tag>
   <elementGuidId>36cb6823-4674-419a-bc44-dac27fb0fb4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moduleName-23-nav']/div/div/div/section[5]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#moduleName-23-nav > div.moduleLinkDiv > div.linkBody > div.section > section:nth-of-type(5) > ul.moduleLinkInnerDiv > li.moduleLinkInnerList > a.moduleLinkPageName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Event&quot;s] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d44edd90-2c3e-4e6b-a59b-df7fb2657fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../t/23-1-1/Events/Event.do?method=load&amp;eventId=</value>
      <webElementGuid>d07ca72e-c77f-4f0a-9f8b-892ce4affe22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduleLinkPageName</value>
      <webElementGuid>b32410a9-cb2b-459b-a099-c37fa7dffd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-moduleid</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>8c70e178-d446-40ca-9a78-e3ce2662585e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maintabid</name>
      <type>Main</type>
      <value>775</value>
      <webElementGuid>cdc6bf38-6c3e-433b-8b08-02d2d68f4427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtabid</name>
      <type>Main</type>
      <value>776</value>
      <webElementGuid>153893c2-c85a-4321-9dfc-1f00f127c5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modulename</name>
      <type>Main</type>
      <value>Events</value>
      <webElementGuid>f12148b7-665a-470d-9b6d-0276cc87b553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event</value>
      <webElementGuid>598203f5-31b3-446a-b5d6-262f3afb4900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleName-23-nav&quot;)/div[@class=&quot;moduleLinkDiv&quot;]/div[@class=&quot;linkBody&quot;]/div[@class=&quot;section&quot;]/section[5]/ul[@class=&quot;moduleLinkInnerDiv&quot;]/li[@class=&quot;moduleLinkInnerList&quot;]/a[@class=&quot;moduleLinkPageName&quot;]</value>
      <webElementGuid>487f019c-6ae0-4119-a6b3-f0b23f473f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Event/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>ab87c92e-13ca-44d1-8dcb-538ab5a5e407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moduleName-23-nav']/div/div/div/section[5]/ul/li/a</value>
      <webElementGuid>58e4d0c7-21cc-41e5-be6c-0de3ea2e4fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Event')])[14]</value>
      <webElementGuid>6ffbbe6b-2d14-48c8-9782-e2f8f5853ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[13]/following::a[1]</value>
      <webElementGuid>aab757f2-2aa8-46e9-8749-a132dab9ace3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservation'])[4]/following::a[1]</value>
      <webElementGuid>73194075-1e22-431e-b074-b24619b145b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick Reservation'])[1]/preceding::a[1]</value>
      <webElementGuid>c91503a4-a897-4e68-a739-351e59160c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservation'])[5]/preceding::a[2]</value>
      <webElementGuid>1bbaad37-db4f-44b6-8732-6173623dacea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../../t/23-1-1/Events/Event.do?method=load&amp;eventId=')])[2]</value>
      <webElementGuid>49c79f51-aa65-43b8-b7b1-734aeeb49aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/section[5]/ul/li/a</value>
      <webElementGuid>f4481c41-025f-443f-86dd-c8c593993874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../t/23-1-1/Events/Event.do?method=load&amp;eventId=' and (text() = 'Event' or . = 'Event')]</value>
      <webElementGuid>e8133a7a-a244-49ef-8cf1-f661ff03d95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
