<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Add Event Session and schedules_Dial_b9696d</name>
   <tag></tag>
   <elementGuidId>2594d618-274f-4836-b5ed-6790d50ff7c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='DialogWindowFrame_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DialogWindowFrame_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;DialogWindowFrame_0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1d236795-eeb5-47c2-9aee-1477edab5a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5932fa39-8b63-4f06-8c7d-df32e74da8ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DialogWindowFrame_0</value>
      <webElementGuid>92968847-08ec-4d05-8915-76033b882369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DialogWindowFrame_0</value>
      <webElementGuid>6db65ced-3111-415b-8489-596f6c8d09b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nexusautomation1.sibisoft.com:9071/AR1-C4/t/23-1-1/Events/EventSeating.do?method=load&amp;eventId=7289</value>
      <webElementGuid>d4f664a9-e33a-4001-b658-0970a9e0dabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isopen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97a7f38c-d264-4828-bbc6-6cc46c307bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DialogWindowFrame_0&quot;)</value>
      <webElementGuid>ad78a2e1-9151-43ac-b734-43fb99bf27e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Event/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>3466ba12-9441-40dd-8ef1-59c63cca487a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='DialogWindowFrame_0']</value>
      <webElementGuid>735bd1b5-4bd8-4b62-a923-14ebfff4d607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-body-div_0']/iframe</value>
      <webElementGuid>785c3fb1-d40e-4ea4-88f8-322e603677c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div[2]/iframe</value>
      <webElementGuid>1db82d9e-5686-4afe-a657-4d4d78921c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'DialogWindowFrame_0' and @name = 'DialogWindowFrame_0' and @src = 'https://nexusautomation1.sibisoft.com:9071/AR1-C4/t/23-1-1/Events/EventSeating.do?method=load&amp;eventId=7289']</value>
      <webElementGuid>6333031d-f87a-4949-8ac9-f88cc7dedc53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
