<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>49ab4696-df25-4ad7-a715-5de78fe470e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick=&quot;showTimer2('startTime','endTime','_PAST','_EMPTY','_DISABLEBLUR','_WARN')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.input-group-addon > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>56a046a7-4fd9-41af-9cf4-0f198853d509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/clock.gif</value>
      <webElementGuid>a60ef209-53b1-4e75-8d1b-2706c5e82678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>fe0fe08b-2495-4baf-9670-fe6163e2606b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>d98f1941-9a69-4000-85b6-2ab92efb6c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d18074d-6c8c-4fae-bc0b-b5e852bc28a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>33bb13bd-12d0-40b4-a8c5-4dd747a805d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showTimer2('startTime','endTime','_PAST','_EMPTY','_DISABLEBLUR','_WARN')</value>
      <webElementGuid>41138608-d116-4d4e-8a3c-7da440225f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSeating&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-4 col-sm-4&quot;]/div[@class=&quot;input-group&quot;]/span[@class=&quot;input-group-addon&quot;]/img[1]</value>
      <webElementGuid>3428a7f8-af17-4cd0-a4d8-1e5515bad424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Event/iframe_Add Event Session and schedules_Dial_b9696d</value>
      <webElementGuid>aa0f4ffd-afc5-4d5b-95c9-05210a3e4d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick=&quot;showTimer2('startTime','endTime','_PAST','_EMPTY','_DISABLEBLUR','_WARN')&quot;]</value>
      <webElementGuid>daaa6468-1338-4721-983c-f0ade40e840f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSeating']/div[5]/div/div[3]/div/div/span/img</value>
      <webElementGuid>51c8910d-550f-4874-b0e2-1ae38c5e8e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>699d6c99-70c7-492b-bb23-1066e9cee321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/clock.gif']</value>
      <webElementGuid>229911d6-2191-4e07-876a-f75179410027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
