<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allow different timings for each day__13ef44</name>
   <tag></tag>
   <elementGuidId>a0a02f5a-5288-4121-8f78-3ca3334a031b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='allowResOnDiferentSessionOnDifferentDays']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#allowResOnDiferentSessionOnDifferentDays</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Allow Reservations on different session on different days&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9633d02-e9db-41b4-919b-2599c6099012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>allowResOnDiferentSessionOnDifferentDays</value>
      <webElementGuid>aa620838-5fe2-4684-9e14-c87241f2b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>e7a85060-5a6d-453b-89d5-3e7c7bc26390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86e48954-262f-4257-8bfc-29f4d16a68d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allowResOnDiferentSessionOnDifferentDays</value>
      <webElementGuid>713e216b-2c94-48b4-9f94-365a38ee1175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_oldvalue</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>0bbc3867-0f4b-42c7-b6fa-6ca950c02233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allowResOnDiferentSessionOnDifferentDays&quot;)</value>
      <webElementGuid>ca76b0ad-9b3b-475f-9bfc-4b102555ab1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Event/iframe_Confirm_landingFrame</value>
      <webElementGuid>36f6df1c-c0b5-4ffe-b912-0a6b9453cb21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='allowResOnDiferentSessionOnDifferentDays']</value>
      <webElementGuid>d61bca48-d25d-4414-8d6c-eca2ade7f284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allowResOnDiferentSessionOnDifferentDaysDiv']/div/input</value>
      <webElementGuid>da0c3c31-4ee7-4008-9ee7-49544dc43a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>36c6257d-c8f1-4d37-947c-38191588a179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'allowResOnDiferentSessionOnDifferentDays' and @type = 'checkbox' and @id = 'allowResOnDiferentSessionOnDifferentDays']</value>
      <webElementGuid>8bbfcb07-84d0-4478-a68b-6280aed90a18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
