<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DAC</name>
   <tag></tag>
   <elementGuidId>2989bfe6-c060-40c9-90dc-6ed2d50533d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.dropdown-toggle.navSiteSelect.custom-select-trigger.newNavSiteChange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#v-pills-tab >> internal:role=button[name=&quot;DAC&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e384b67-8a7e-430c-bb4c-d48b50c4a682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle navSiteSelect custom-select-trigger newNavSiteChange</value>
      <webElementGuid>9daf79e8-8feb-4ac3-bb5e-8ba5aaa92d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>201a9d91-9fd2-449e-a32f-8304e24df878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-siteid</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>43a7218c-3e79-4746-b228-0f1390b286dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				 DAC
			</value>
      <webElementGuid>c52d43d3-fd43-48a0-94dd-8bf6879f40d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v-pills-tab&quot;)/div[@class=&quot;fixedLeftNav&quot;]/div[@class=&quot;sites&quot;]/div[@class=&quot;dropdown siteDropdown custom-select&quot;]/button[@class=&quot;btn dropdown-toggle navSiteSelect custom-select-trigger newNavSiteChange&quot;]</value>
      <webElementGuid>3081c5d3-cca6-4b8d-b799-2a8436bc6a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Login/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>4b601281-48c4-495b-9810-e21951eb78c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>98271a2c-dd2a-4eea-93ea-8ef3636a2614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v-pills-tab']/div/div/div/button</value>
      <webElementGuid>13f55d88-1d28-46eb-a3c0-b832593cf06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a Site'])[1]/following::button[1]</value>
      <webElementGuid>8b73fc91-e0d4-4ef1-9f20-b4ef421de18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAC'])[10]/preceding::button[1]</value>
      <webElementGuid>c5b9ed57-8137-4a17-82a0-8ea89f90ca63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/button</value>
      <webElementGuid>ea7b8ce0-e750-400d-a7b8-e00ae337002f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
				 DAC
			' or . = '
				 DAC
			')]</value>
      <webElementGuid>87ff8aca-c725-4d30-8046-a774e697f2c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
