<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Create Invoice</name>
   <tag></tag>
   <elementGuidId>eea5238f-e64e-497f-af9d-3c510ca2fa96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moduleName-4-nav']/div/div/div/section[7]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Create Invoice&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f73e629e-997d-4d3f-9e0d-74993319d1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../t/4-1-1/Accounting/AP/invoice.jsp</value>
      <webElementGuid>c30f0b77-bac9-415e-b0fd-8fa1acc1e8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduleLinkPageName</value>
      <webElementGuid>783a2889-44a2-4830-920e-e377ee8fa835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-moduleid</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4ba6bca4-4618-4d0b-b79a-7e77b9d3eb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maintabid</name>
      <type>Main</type>
      <value>67</value>
      <webElementGuid>4e7e7d28-fc91-4eba-88a6-5192e0f2eabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtabid</name>
      <type>Main</type>
      <value>479</value>
      <webElementGuid>6a27ea0f-23c8-4ce7-816c-7e5f0ff69ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modulename</name>
      <type>Main</type>
      <value>Accounts Payable</value>
      <webElementGuid>f0500e35-4c17-4f18-81cd-8a85bc074cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Invoice</value>
      <webElementGuid>3eba67fd-544b-439a-ad2e-e5b6b141e2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleName-4-nav&quot;)/div[@class=&quot;moduleLinkDiv&quot;]/div[@class=&quot;linkBody&quot;]/div[@class=&quot;section&quot;]/section[7]/ul[@class=&quot;moduleLinkInnerDiv&quot;]/li[@class=&quot;moduleLinkInnerList&quot;]/a[@class=&quot;moduleLinkPageName&quot;]</value>
      <webElementGuid>6b303efd-3548-4526-8e18-73b0fd890683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Create Invoice/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>76c21961-d46a-4154-9e81-79468a02b3fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moduleName-4-nav']/div/div/div/section[7]/ul/li[3]/a</value>
      <webElementGuid>08be57ff-5cce-45e3-b5ce-49e843758cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Create Invoice')]</value>
      <webElementGuid>7910d334-b16e-4ad1-a82c-c9f0d65e3f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[6]/following::a[3]</value>
      <webElementGuid>e287c915-016b-4552-b2bf-a065ce612fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchases'])[1]/following::a[3]</value>
      <webElementGuid>c5b66fa2-86bc-4bd4-93d4-e1ee8074b5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Vendor'])[1]/preceding::a[1]</value>
      <webElementGuid>d8f1fd77-31a2-4359-9055-7313e6b44dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Mapping'])[1]/preceding::a[2]</value>
      <webElementGuid>434e2c15-e6b0-46ff-8044-06dd52a1fa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create Invoice']/parent::*</value>
      <webElementGuid>8ff7b8b4-163d-4609-bce7-86142676dc89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../t/4-1-1/Accounting/AP/invoice.jsp')]</value>
      <webElementGuid>0ce617a7-73cb-41bd-986b-125e785044ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[7]/ul/li[3]/a</value>
      <webElementGuid>25f748fd-f2de-43e2-841b-94aa14d0ac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../t/4-1-1/Accounting/AP/invoice.jsp' and (text() = 'Create Invoice' or . = 'Create Invoice')]</value>
      <webElementGuid>1a48d596-43a1-4f62-98d7-fb508424345d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
