<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Confirm_landingFrame</name>
   <tag></tag>
   <elementGuidId>8be521c5-9916-4e47-90b0-b85b24eb3d72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='landingFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#landingFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;landingFrame&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1293028b-dbc6-494d-981f-7b6b8ed978dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>e899acd0-c6a1-4dbd-9630-c941b1bbac38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landingFrame</value>
      <webElementGuid>63a3192b-a564-4c7a-bdad-d62195314b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../t/4-1-1/Accounting/AP/invoice.jsp</value>
      <webElementGuid>5f3bc5bf-a925-483e-8300-8f9809156ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>closeIt(this.contentWindow.location)</value>
      <webElementGuid>4d0e1ccf-d95e-433c-8cc5-b2efe92349c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingFrame&quot;)</value>
      <webElementGuid>6a625079-f62e-4fd2-9ca3-7ef826cf4e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Create Invoice/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>dd57b3eb-bbdb-4d44-8184-7f44980ed3d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='landingFrame']</value>
      <webElementGuid>f85f2b88-7daa-4cb2-9307-4495b71c9e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/iframe</value>
      <webElementGuid>6831d14f-e115-4ce6-8199-0e20e2f36571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/iframe</value>
      <webElementGuid>b7bf4b8d-4b05-44c8-b9c5-2022a8aa5435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'landingFrame' and @name = 'landingFrame' and @src = '../../t/4-1-1/Accounting/AP/invoice.jsp']</value>
      <webElementGuid>809e3084-6714-4e2c-9f79-e3bb81ad4416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
