<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Course Setup</name>
   <tag></tag>
   <elementGuidId>e2742303-7247-40b3-93d4-d7712daa7e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moduleName-21-nav']/div/div/div/section/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Course Setup&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62c8f660-130d-45a7-b2be-ffd5a6c9968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../t/21-1-1/Sports/saveCourseSetup.do?method=browse</value>
      <webElementGuid>155970d7-c220-4937-b432-447c19c7c359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduleLinkPageName</value>
      <webElementGuid>273b7120-9919-41f2-95ef-3a60ff985576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-moduleid</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>0a4605bc-8c85-4792-bfd9-f4371778656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maintabid</name>
      <type>Main</type>
      <value>746</value>
      <webElementGuid>aaec814a-52e3-46f7-9a98-be4b890ad5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtabid</name>
      <type>Main</type>
      <value>747</value>
      <webElementGuid>59cd88ad-8adb-4b6f-8610-04000b177ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modulename</name>
      <type>Main</type>
      <value>Tee Time</value>
      <webElementGuid>0546dd63-2168-42af-82d7-5f7ea4d184eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Course Setup</value>
      <webElementGuid>3505a230-46a3-40e7-855a-f2bbb163b897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleName-21-nav&quot;)/div[@class=&quot;moduleLinkDiv&quot;]/div[@class=&quot;linkBody&quot;]/div[@class=&quot;section&quot;]/section[1]/ul[@class=&quot;moduleLinkInnerDiv&quot;]/li[@class=&quot;moduleLinkInnerList&quot;]/a[@class=&quot;moduleLinkPageName&quot;]</value>
      <webElementGuid>e43c4028-fb02-4cc1-9bb7-fd2e61c98133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>b2d619b6-8faa-4854-9752-5a13d1ec3bc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moduleName-21-nav']/div/div/div/section/ul/li[2]/a</value>
      <webElementGuid>0b7dfb38-0f73-43f0-8664-a0d7d4cdfc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Course Setup')]</value>
      <webElementGuid>c6f341e8-414a-495d-9794-43bb7fc10c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Block Times'])[4]/following::a[1]</value>
      <webElementGuid>396702e4-7efd-49e3-b7f8-7ed6acc81135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[34]/following::a[2]</value>
      <webElementGuid>a8889484-250d-43c0-8ea6-b5009801b901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Templates'])[9]/preceding::a[1]</value>
      <webElementGuid>aef214cc-a519-4350-b4de-1ab14cf53169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Setup'])[2]/preceding::a[2]</value>
      <webElementGuid>e0bc39c0-18b7-457a-acb7-6e7acd82f2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Course Setup']/parent::*</value>
      <webElementGuid>e115909f-dc3e-4ed3-89dd-d12e43cc3aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../../t/21-1-1/Sports/saveCourseSetup.do?method=browse')]</value>
      <webElementGuid>6b80f7c9-1abf-4186-a9d7-284398307978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div/div/section/ul/li[2]/a</value>
      <webElementGuid>a21522a8-44ec-4d7a-a601-48a16f608fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../t/21-1-1/Sports/saveCourseSetup.do?method=browse' and (text() = 'Course Setup' or . = 'Course Setup')]</value>
      <webElementGuid>373d83a7-1a1b-4b1c-8671-b17f28c2699a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
