<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nicklaus Cup</name>
   <tag></tag>
   <elementGuidId>9661e2af-dad4-4de7-b354-75e27204d0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ui-id-24</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68d5f62c-1456-4bd6-b2e5-f62a330fe24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-24</value>
      <webElementGuid>ebebeb95-567c-4e25-bdb3-1ea6f3bbc87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9b7b6d07-fa87-4e33-ba7f-09fd851a128d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>70c90ffb-1c6b-4d58-a4ac-0c370157b621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nicklaus Cup</value>
      <webElementGuid>b3a2408b-4245-43c3-87f0-0b32673554cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-24&quot;)</value>
      <webElementGuid>08208a4b-7473-4a86-84ea-ef61bc42627c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>70c4102f-c03e-45ea-a197-a88e11ef5149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-24']</value>
      <webElementGuid>c1ab5dee-5cf1-43e3-9a02-986117940851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-1']/li[2]/a</value>
      <webElementGuid>51143376-0d87-4bf8-bfd9-371eb4fc4719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nicklaus Cup')]</value>
      <webElementGuid>864bc58c-36ff-4a28-9e1a-19cb162cd4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new'])[1]/following::a[1]</value>
      <webElementGuid>d24b7295-328a-4aaa-aa1e-08a9ffc4bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::a[2]</value>
      <webElementGuid>d792a9f8-31d8-4451-aa78-fd3f47855e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike Glove Tour Classic'])[1]/preceding::a[1]</value>
      <webElementGuid>c70b6083-c120-4862-8b75-2cdcdecab956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nike Gloves'])[1]/preceding::a[2]</value>
      <webElementGuid>1c04054f-f3a6-4db3-b854-0c1382788a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nicklaus Cup']/parent::*</value>
      <webElementGuid>46954e19-cde1-4e6c-b4f2-0b7456ab7816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/ul/li[2]/a</value>
      <webElementGuid>65c11a5e-3152-4162-af78-c5f356fb2a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ui-id-24' and (text() = 'Nicklaus Cup' or . = 'Nicklaus Cup')]</value>
      <webElementGuid>2131af1d-af25-4bb3-bb3f-5f1e4ccda8a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
