<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Member_0chargeItemAmountGreenFee9Hole_1618b6</name>
   <tag></tag>
   <elementGuidId>f0890edf-bf96-4807-9712-c05adfbb8ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='0chargeItemAmountGreenFee9HolesForMemberAndGuest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0chargeItemAmountGreenFee9HolesForMemberAndGuest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\30 chargeItemAmountGreenFee9HolesForMemberAndGuest&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8551d398-026a-4e17-b380-0a946e4add2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0chargeItemAmountGreenFee9HolesForMemberAndGuest</value>
      <webElementGuid>9186fb76-7157-4f6a-84e4-ef95cd9b7ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>ad763264-0efa-4398-b2fc-48eadcf88390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ec75a28e-b4d5-4559-b499-abb65e301507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>71f2c75c-b969-4014-8a6e-1b489ce175ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-right positiveDecimalNumbersOnly</value>
      <webElementGuid>5c749715-664d-4faa-b749-8e4c8c401cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a819b718-95e1-46cf-87b4-b3d2ffb335e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0chargeItemAmountGreenFee9HolesForMemberAndGuest&quot;)</value>
      <webElementGuid>d74f51ae-da24-4122-a1cd-f199e1c8d82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>cc115ffc-4958-4247-ace8-b6eab8849358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='0chargeItemAmountGreenFee9HolesForMemberAndGuest']</value>
      <webElementGuid>24850ca6-88c5-4509-a3a5-91871f8aa1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='0GreenFee9HolesAmountValueInCoursePerPersonChargesForMemberAndGuest']/input</value>
      <webElementGuid>56100612-d19b-44c1-aaba-636e48ff70e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>878b4923-947a-4acd-a557-692b3de29f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '0chargeItemAmountGreenFee9HolesForMemberAndGuest' and @type = 'number']</value>
      <webElementGuid>7bde5c5a-7126-45de-b54e-6f3105e091c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
