<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Guest_ysearchinput1chargeItemNameGree_09c205</name>
   <tag></tag>
   <elementGuidId>48c7f1dc-4228-4714-abe8-389173fc034f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>499c74b9-79a9-470b-a413-c54713d3fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98e5a501-2556-4c0b-b0f2-a8f86e4b2ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      <webElementGuid>a71c144b-99af-4db4-bd60-2afb60e8ca3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ysearchinput</value>
      <webElementGuid>91ba2773-baa1-4741-9907-91cc0eac4c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest&quot;)</value>
      <webElementGuid>24039b12-e9da-4c7c-b922-00f0c9ba2c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>97dc57ac-9152-429a-86a6-c1d7348b7826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      <webElementGuid>2a84d495-2fdb-4d76-bade-2407fd2650c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ysearchautocomplete1chargeItemNameGreenFee9HolesForMemberAndGuest']/input</value>
      <webElementGuid>093b324e-af9c-4292-9591-1b7c2d9d9c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/input</value>
      <webElementGuid>380c38fc-57e3-4e84-b6a3-55af8cd102f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ysearchinput1chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      <webElementGuid>7f13db08-feea-4ed6-8085-e715118f6d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
