<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Guest_ysearchinput1chargeItemNameGree_a72fe8</name>
   <tag></tag>
   <elementGuidId>a0add549-6642-4b79-a74c-72fd4d7e8eb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>515de4a7-27bd-4935-833f-98adb76eaf5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3520eba-5f73-4b76-a6a4-12a1891a8b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest</value>
      <webElementGuid>a48af082-509b-45ea-9231-3af5b1981996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ysearchinput</value>
      <webElementGuid>fefbf628-edb4-4094-807a-8e2e1c6ea657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest&quot;)</value>
      <webElementGuid>0c26bf34-572a-4b79-a442-3b0e447ab26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>e7c9c873-bbfe-48b4-beb9-6ac83f590f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest']</value>
      <webElementGuid>6a609b15-9fb3-4261-ab5e-87b2d4cca5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ysearchautocomplete1chargeItemNameGreenFee18HolesForMemberAndGuest']/input</value>
      <webElementGuid>692d0f1d-9359-4cab-8ac4-87088c2abc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/div/input</value>
      <webElementGuid>bc8538ad-a798-452e-b63a-b869dced4615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ysearchinput1chargeItemNameGreenFee18HolesForMemberAndGuest']</value>
      <webElementGuid>dc40fb51-6a29-4e4d-b0ad-db5820be61dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
