<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Member_ysearchinput0chargeItemNameGre_022940</name>
   <tag></tag>
   <elementGuidId>01ae1b6a-ff66-4abd-9032-8cc85f3cc316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7088301-feeb-4939-bcf6-119816236b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02e3793b-f700-4afb-8f6d-31af0a0b52b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest</value>
      <webElementGuid>4911a07b-011e-464a-b66f-e01e6a79e490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ysearchinput</value>
      <webElementGuid>695cccfa-7132-4472-bb96-b37b32f24a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest&quot;)</value>
      <webElementGuid>ad8cc00b-6493-4e08-a8d2-f766bc3e2aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Course Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>bd4ac059-bc2a-4281-9a20-975cddf9ad98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      <webElementGuid>be2087b5-0f17-4615-9ba1-eb6d440d70c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ysearchautocomplete0chargeItemNameGreenFee9HolesForMemberAndGuest']/input</value>
      <webElementGuid>b944fb03-cd34-4f65-a17e-948a7efcee29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>4d69e706-2765-4519-b45c-2cbeed6e4b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ysearchinput0chargeItemNameGreenFee9HolesForMemberAndGuest']</value>
      <webElementGuid>20701d04-d612-46ce-bb67-d70c2c6ed739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
