<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Block slots after shotgun time upto_s_0db333</name>
   <tag></tag>
   <elementGuidId>00dba72e-6901-4a16-93e7-1e244e58bc23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saveOrUpdateButtonForShotgun']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saveOrUpdateButtonForShotgun</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f94a4c8-613a-45ea-a90f-0f1e920da83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8075db28-54a7-4bb0-b32f-2a8609b737bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saveOrUpdateButtonForShotgun</value>
      <webElementGuid>b39c183e-fefa-401b-a55a-bb511d04ed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>e1c8e6af-8cdb-4135-ad38-af69b5d937f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>16ee2a27-4baf-42bf-ac03-c0741ffd511b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>editShotGunBlockInformation();</value>
      <webElementGuid>de7a4be1-d5dd-4fc7-9620-5dd7acf90eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saveOrUpdateButtonForShotgun&quot;)</value>
      <webElementGuid>79979f35-e0f8-4065-887a-52cf020950c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet Template Setup/iframe_Confirm_landingFrame</value>
      <webElementGuid>3c919b9d-3811-4856-90d3-d6d07333b3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saveOrUpdateButtonForShotgun']</value>
      <webElementGuid>64668f7f-ce1e-4d2a-b017-d6bbec7efd18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ShotGunBlockTable']/tbody/tr[2]/td/table/tbody/tr[3]/td/input</value>
      <webElementGuid>914fbd11-34a9-4e62-9527-3b4d8098a911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr[2]/td/table/tbody/tr[3]/td/input</value>
      <webElementGuid>d0774b08-2d6f-4b57-8881-000df442dcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'saveOrUpdateButtonForShotgun']</value>
      <webElementGuid>b04e6959-87b8-4264-bde8-184a879deadb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
