<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_null</name>
   <tag></tag>
   <elementGuidId>d0b1d417-1bb1-4305-ab37-a26c496b5fb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\30 &quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2d7b8454-a84f-4433-9d5f-b896225d8b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3213d23b-8384-4ae7-aa69-784062fcf7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>4a7079db-e573-4653-8060-12f3c3b2860b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oncontextmenu</name>
      <type>Main</type>
      <value>UnTip();showEditAndDeleteTable(event,this);</value>
      <webElementGuid>98e444f7-7cab-4747-a905-baa33db0c6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>showToolTip(0,this);</value>
      <webElementGuid>862a4322-b560-4c2f-937a-30a58d47973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>UnTip();</value>
      <webElementGuid>737a194c-09f6-4b7b-ab55-2df098cbbd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>droppable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1cabfee-4620-4c63-862f-934c7a52cf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>timeofslot</name>
      <type>Main</type>
      <value>03:00:00</value>
      <webElementGuid>57af62be-72b0-47cd-8b60-0a940bb772dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>indexofslot</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2d62e88a-2d2e-451b-bc40-30112d1c1105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>92.0%</value>
      <webElementGuid>c116668c-1961-4c63-a6c4-d38d21accd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3d0d2f21-40a1-4d47-a072-d0a1eeb65d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>73a33b50-ddb4-4301-8455-dccbfc674a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>7d149cac-97ff-4a49-9f20-9b9ecfa87ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bgcolor</name>
      <type>Main</type>
      <value>#FFFFF1</value>
      <webElementGuid>0ca91c4b-66a5-45ec-9ac0-e8fbea2092c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>teeoff</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78f2296e-582e-4a58-809d-743417041318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>teeofflabel</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d22a530b-0a26-4aa4-83cf-814e0225a94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isdoubletee</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11ff780b-19ae-4933-95f1-a14a7d72a572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isemptyslot</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de360368-9c24-4653-903f-f6de86292b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossoverallowed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>381d1d81-ca2a-4280-b564-4c16abb4cfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uitimeofslot</name>
      <type>Main</type>
      <value>03:00 AM</value>
      <webElementGuid>35e0db85-b752-4456-bff9-f8c6ecbbdb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>startOrStopHighlighting()</value>
      <webElementGuid>d8aac7ed-4439-48ee-b125-0b19ea0c94dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frostblockid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1dcfd6e-f607-4708-ac04-a1f13722706d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeofslot</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>86f68068-2938-428e-aa14-de6629b952c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
													
													 
														null
													
												
												</value>
      <webElementGuid>3c6d2aad-15b5-4a22-9ff5-2974e19cdbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)</value>
      <webElementGuid>448490da-b21d-490b-ac34-428387286ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet Template Setup/iframe_Applied On 0 Day(s)_frameTeesheetTemplate0</value>
      <webElementGuid>6307327f-984a-42fa-95a3-15d365a429a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='0']</value>
      <webElementGuid>39d60ec5-210e-465e-919c-779098d78e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='TeeSheetTemplateForm']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td[5]</value>
      <webElementGuid>92cdeae5-e07d-4334-acf9-92b084fd2e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single 9'])[1]/following::td[1]</value>
      <webElementGuid>4ddc0682-2c7b-42e6-993b-59514ad3156d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/following::td[2]</value>
      <webElementGuid>b57e5830-a3bd-4c18-9014-9030aa2d167b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[2]/preceding::td[3]</value>
      <webElementGuid>dadbde45-085f-4bbe-b657-82f62cc7fe1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single 9'])[2]/preceding::td[4]</value>
      <webElementGuid>6e93e720-614b-468f-b21b-38265d787cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]</value>
      <webElementGuid>690398e1-b88b-4cf2-ab60-4a594f0c9bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = '0' and (text() = '
													
													 
														null
													
												
												' or . = '
													
													 
														null
													
												
												')]</value>
      <webElementGuid>e3c839a6-b35d-40a7-b56a-8dee86367ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
