<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Shotgun</name>
   <tag></tag>
   <elementGuidId>b9aeaa5f-0328-4619-bf90-97ca0ad82222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;submitSelectedMode('Shotgun')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.content.blockModes.hideOnEvent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Shotgun&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aba2f830-4f85-47d3-9d52-bf36d60ad3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content blockModes hideOnEvent</value>
      <webElementGuid>9b1f0206-be36-40bb-9bb5-bc261b10b5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitSelectedMode('Shotgun')</value>
      <webElementGuid>ebb18052-905d-4b07-85fd-d7e67f9868c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Shotgun
			</value>
      <webElementGuid>258112e9-d1d0-44f4-81b4-defa94a8e14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modesTable&quot;)/tbody[1]/tr[3]/td[@class=&quot;content blockModes hideOnEvent&quot;]</value>
      <webElementGuid>23d8f6ce-aac4-4c1b-af62-8edcb956cbbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet Template Setup/iframe_Applied On 0 Day(s)_frameTeesheetTemplate0</value>
      <webElementGuid>06a94505-a8c3-4379-89af-72b65760416c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;submitSelectedMode('Shotgun')&quot;]</value>
      <webElementGuid>2afb8202-5aa0-4ec7-8452-865d49740176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='modesTable']/tbody/tr[3]/td</value>
      <webElementGuid>b7d21112-c6fe-47d6-965d-9bdc9a3b788b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lottery'])[1]/following::td[1]</value>
      <webElementGuid>8acace1f-5ef1-46bc-9643-45eb23c4cbb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Block'])[1]/following::td[2]</value>
      <webElementGuid>b3ad5af8-13ab-4235-96b0-4f4ae1825dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Block'])[1]/preceding::td[1]</value>
      <webElementGuid>cfac80cd-c66c-4a4c-a39a-00deeb01ce05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Tees'])[1]/preceding::td[2]</value>
      <webElementGuid>7bd91fd6-db7b-4a23-9beb-f17d87af9303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shotgun']/parent::*</value>
      <webElementGuid>b0e0e3d1-f326-4705-bbca-772cb1d52bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/table/tbody/tr[3]/td</value>
      <webElementGuid>3c998c3e-e9aa-4f27-b657-74d6958de085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
				Shotgun
			' or . = '
				Shotgun
			')]</value>
      <webElementGuid>7e4955a5-234c-485d-a65e-c17abab0bef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
