<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tee Sheet</name>
   <tag></tag>
   <elementGuidId>5cf832ec-e822-4953-b167-6678ffd5ca3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='moduleName-21-nav']/div/div/div/section[10]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tee Sheet&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e213265-c84f-48bb-b0ad-d18a094b9436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../../t/21-1-1/Sports/NewTeeSheetForTeeTime.do?method=getTeeSheetContainer</value>
      <webElementGuid>813eb26d-26f3-497e-91db-b2218aeefee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moduleLinkPageName</value>
      <webElementGuid>f1fba1eb-b9da-4345-80ed-9bcf17dcfbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-moduleid</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>563d866c-deef-4df8-9836-e89484b25322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maintabid</name>
      <type>Main</type>
      <value>742</value>
      <webElementGuid>1c42801e-b8c3-4cad-a625-89a912da724a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-subtabid</name>
      <type>Main</type>
      <value>1108</value>
      <webElementGuid>a4f4ace4-4cd4-47f7-82a2-79cafa426ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modulename</name>
      <type>Main</type>
      <value>Tee Time</value>
      <webElementGuid>b16e8ea6-a0a4-47a8-b342-379c52a190b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tee Sheet</value>
      <webElementGuid>c18c7fe0-58c8-4d2e-9eaa-5c09a145c0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleName-21-nav&quot;)/div[@class=&quot;moduleLinkDiv&quot;]/div[@class=&quot;linkBody&quot;]/div[@class=&quot;section&quot;]/section[10]/ul[@class=&quot;moduleLinkInnerDiv&quot;]/li[@class=&quot;moduleLinkInnerList&quot;]/a[@class=&quot;moduleLinkPageName&quot;]</value>
      <webElementGuid>db632d0c-7735-4e19-b5c1-8a7b2132d9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet/iframe_Powered by Northstar Club Management_21cbe3</value>
      <webElementGuid>49cd20a3-3b2b-4b20-b96d-ed070eb12d4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='moduleName-21-nav']/div/div/div/section[10]/ul/li[2]/a</value>
      <webElementGuid>7c5a4914-57c4-4652-ab60-d7cc5cd4bf1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Tee Sheet')])[7]</value>
      <webElementGuid>b686adaf-3217-4827-914d-0c81a183a9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Reservations'])[3]/following::a[1]</value>
      <webElementGuid>8cdb0b49-809e-4867-bce1-b2a305a1bc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reservations'])[3]/following::a[2]</value>
      <webElementGuid>22dadc98-1581-4713-9bb1-5482cc4b751a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activities Schedule'])[1]/preceding::a[1]</value>
      <webElementGuid>8bf85fe4-d5b2-4c8e-92ab-5e82fd74c350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daily View'])[1]/preceding::a[1]</value>
      <webElementGuid>e4901c48-9302-4714-b612-3aba817c9d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '../../t/21-1-1/Sports/NewTeeSheetForTeeTime.do?method=getTeeSheetContainer')])[2]</value>
      <webElementGuid>22e842ba-7331-48fc-955d-f6ad6aa2742d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/div/div/div/section[10]/ul/li[2]/a</value>
      <webElementGuid>f800a495-1961-44c2-8b1f-e798e91b1b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../../t/21-1-1/Sports/NewTeeSheetForTeeTime.do?method=getTeeSheetContainer' and (text() = 'Tee Sheet' or . = 'Tee Sheet')]</value>
      <webElementGuid>31a30b8a-b746-4d8e-9eb3-3648eff88ce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
