<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Lottery Requests_TransparentBlock</name>
   <tag></tag>
   <elementGuidId>0c30a0cc-6698-464a-9d66-42904aa0df7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TransparentBlock']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TransparentBlock</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TransparentBlock</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c49463a-59e6-4cd3-9aef-aef058b808bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TransparentBlock</value>
      <webElementGuid>b290dbf5-410d-4fe1-9da1-6744cb2cfb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TransparentBlock&quot;)</value>
      <webElementGuid>bb6c2c75-8b76-42b7-9680-4e007af22267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet/iframe_Confirm_landingFrame</value>
      <webElementGuid>c0d3d935-23c7-4f5b-918e-b8a7de4620af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='TransparentBlock']</value>
      <webElementGuid>e6348fd4-fcc7-426f-94ee-380e8d86a40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divProgressBar']/div</value>
      <webElementGuid>79374d5c-4dd2-4e4c-babd-c67f55281698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div</value>
      <webElementGuid>a06a16e5-3456-4ff0-8dbc-f5e70c1b5693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'TransparentBlock']</value>
      <webElementGuid>fd9f37aa-5893-454c-b322-e36b8cbc2a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
