<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , modalFrame, , ))_modalFrame</name>
   <tag></tag>
   <elementGuidId>54cc7995-38eb-4739-898b-96b34cbe46c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='modalFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modalFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modalFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3650ca01-aa36-49c7-b49f-1e8d7719f2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modalFrame</value>
      <webElementGuid>965fc9f3-ad0e-4ccb-b15d-ad294ab45fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cbab307f-57fb-4c50-9ecf-779a906c7863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>466634dd-6913-4406-b1bd-a1200bfc3d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8215c1ed-3e0d-4ac2-810f-024031423d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0cb548b1-5adc-4888-9795-984f34a1fe04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>15f72127-4946-47e9-9bbd-87cafa56872f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>54bd8c26-485f-4d67-a88b-12fc7ca63357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Sports/ReservationScreen.do?method=newReservation&amp;courseId=50&amp;reservationStartTime=06:00 AM&amp;reservationDate=12/05/2025&amp;groupId=0&amp;clientId=18&amp;holes=18&amp;teeOff=1&amp;teeOffLabel=1&amp;serverId=null&amp;reservationParameters=&amp;teeTimesReservationView=Quick Modified&amp;reservationOnCrossOver=false&amp;mode=1&amp;suppressEmailDefaultValue=&amp;memberId=0&amp;itineraryId=0&amp;disabledItineraryContl=false&amp;isReservationTimeSqueezed=false&amp;timeIntervalOrder=1&amp;isFromMembershipScreen=false&amp;availableHole=null&amp;hideTees=false&amp;configureSlotsForGroupBlock=0&amp;teeOffLabels=1&amp;playerGroups=</value>
      <webElementGuid>5edf35da-10a1-49ee-87d5-40751cfdb195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalFrame&quot;)</value>
      <webElementGuid>118d6740-3c96-4e73-a511-7dd83f5ba1da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet/iframe_Confirm_landingFrame</value>
      <webElementGuid>e15e1a18-dd82-4201-9a7a-6da38e5341bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='modalFrame']</value>
      <webElementGuid>7d8d3282-1676-43aa-bc6e-72ab243692c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalDivForIFrame']/iframe</value>
      <webElementGuid>3592cba1-7a72-4ba0-8798-cc4b6202a6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>70ff3684-982a-4807-91b8-02379ca5ffe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'modalFrame' and @src = '../Sports/ReservationScreen.do?method=newReservation&amp;courseId=50&amp;reservationStartTime=06:00 AM&amp;reservationDate=12/05/2025&amp;groupId=0&amp;clientId=18&amp;holes=18&amp;teeOff=1&amp;teeOffLabel=1&amp;serverId=null&amp;reservationParameters=&amp;teeTimesReservationView=Quick Modified&amp;reservationOnCrossOver=false&amp;mode=1&amp;suppressEmailDefaultValue=&amp;memberId=0&amp;itineraryId=0&amp;disabledItineraryContl=false&amp;isReservationTimeSqueezed=false&amp;timeIntervalOrder=1&amp;isFromMembershipScreen=false&amp;availableHole=null&amp;hideTees=false&amp;configureSlotsForGroupBlock=0&amp;teeOffLabels=1&amp;playerGroups=']</value>
      <webElementGuid>ca27ccac-9246-4fc6-9125-00522c571470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
