<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bill To Player_ysearchinputmemberNumber11</name>
   <tag></tag>
   <elementGuidId>11dba323-91b3-421f-93c3-1fe3bd0d4bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ysearchinputmemberNumber11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ysearchinputmemberNumber11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ysearchinputmemberNumber11</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f26d8510-27fb-4c7a-bae7-fc5ebda4d8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e18cc83-348b-4924-ad13-5289b8a8be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>memberNumber11</value>
      <webElementGuid>4521d16c-bb97-4c0f-9a7d-779fe7e31e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ysearchinputmemberNumber11</value>
      <webElementGuid>4b6bac5b-336f-4a55-9322-8a37f259ee7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ysearchinput ui-autocomplete-input</value>
      <webElementGuid>55bb2d27-33e1-46ad-98e0-944eebe07b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoscroll</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>090aa392-2080-4cc5-9de1-c7132f1fbca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3af854c-bd9d-49b8-876c-df784ae361ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ysearchinputmemberNumber11&quot;)</value>
      <webElementGuid>b6eead4c-b519-47d3-ac33-1c20f3c86dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Tee Sheet/iframe_concat(id(, , modalFrame, , ))_modalFrame</value>
      <webElementGuid>795a0b35-77d8-487f-8ebd-bae767b9a1e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ysearchinputmemberNumber11']</value>
      <webElementGuid>9f061949-9694-415b-8305-f6ff60638146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ysearchautocompletememberNumber11']/input</value>
      <webElementGuid>a6ebc205-b7fa-4572-925f-e8386749b9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/div/input</value>
      <webElementGuid>1e0a5b20-69ef-41fe-ac78-a4dd0c6c758e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'memberNumber11' and @id = 'ysearchinputmemberNumber11']</value>
      <webElementGuid>46c60f61-4e87-41b7-82b3-3cc36fadd715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
